annotations:
  - /home/projects-wrighton/EMERGE/EMERGE_MAGs_v1/Emerge_MAGs_v1/gene_db/Cronin_DRAMv1_annotations.txt
  - /home/projects-wrighton/EMERGE/EMERGE_MAGs_v1/Emerge_MAGs_v1/gene_db/JGI_DRAMv1_annotations.txt
  - /home/projects-wrighton/EMERGE/EMERGE_MAGs_v1/Emerge_MAGs_v1/gene_db/SIP_DRAMv1_annotations.txt
  - /home/projects-wrighton/EMERGE/EMERGE_MAGs_v1/Emerge_MAGs_v1/gene_db/Woodcroft_DRAMv1_annotations.txt
