annotations:
  # - ./resources/test_data/min_annotations_20100900_E1D_12.tsv
  # - ./resources/test_data/min_annotations_3300023248_8.tsv
  - <path>/Cronin_DRAMv1_annotations.txt
  - <path>/JGI_DRAMv1_annotations.txt
  - <path>/SIP_DRAMv1_annotations.txt
  - <path>/Woodcroft_DRAMv1_annotations.txt
dram_to_use: '1_2' # pick 1.2=1_2 or 1.3=1_3 depending on the dram you used
