annotations:
  - /home/projects-wrighton/EMERGE/EMERGE_MAGs_v1/Emerge_MAGs_v1/gene_db/Cronin_DRAMv1_annotations.txt
  - /home/projects-wrighton/EMERGE/EMERGE_MAGs_v1/Emerge_MAGs_v1/gene_db/JGI_DRAMv1_annotations.txt
  - /home/projects-wrighton/EMERGE/EMERGE_MAGs_v1/Emerge_MAGs_v1/gene_db/SIP_DRAMv1_annotations.txt
  - /home/projects-wrighton/EMERGE/EMERGE_MAGs_v1/Emerge_MAGs_v1/gene_db/Woodcroft_DRAMv1_annotations.txt
dram_to_use: '1.2' # pick 1.2 or 1.3 depending on the dram you used
